@baseUrl = http://ec2-18-191-173-110.us-east-2.compute.amazonaws.com:8080
//@baseUrl = http://localhost:8080

### authentication ============================================================
POST {{baseUrl}}/auth/login  HTTP/1.1
content-type: application/json

{
    "email": "seller1",
    "password": "seller1"
}

### regiseer
POST {{baseUrl}}/auth/join  HTTP/1.1
content-type: application/json

{ 
    "name" : "hihihi",
    "email" : "seller1",
    "password" : "seller1",
    "type" : "seller"
}

### logout
GET {{baseUrl}}/auth/logout  HTTP/1.1

<!-- response data format
{
  "res": "success",
  "msg": "회원가입 성공"
}->

### type check ============================================================
