//@baseUrl = http://ec2-18-191-173-110.us-east-2.compute.amazonaws.com:8080
@baseUrl = http://localhost:8080


///////////////////////////////////////////////////////////////////
// get my order list 
///////////////////////////////////////////////////////////////////
GET {{baseUrl}}/tradeLog/myOrders HTTP/1.1
content-type : application/json

<!-- 
{
  "data": [
    {
      "id": 9,
      "from": 1,
      "to": 2,
      "itemId": 1,
      "orderCount": 3,
      "transactionKey": 1234,
      "createdAt": "2020-05-24T15:49:37.000Z",
      "updatedAt": "2020-05-24T15:49:37.000Z",
      "deletedAt": null,
      "campaignId": null,
      "campaign": null,
      "item": {
        "id": 1,
        "name": "item1"
      },
      "seller": {
        "id": 2,
        "name": "hihihi"
      },
      "consumer": {
        "id": 1,
        "name": "쿠팡"
      }
    },
  ]
}
-->

///////////////////////////////////////////////////////////////////
// get my donation list ( end/ ing)
///////////////////////////////////////////////////////////////////
###
GET {{baseUrl}}/tradeLog/myDonations/end HTTP/1.1
content-type : application/json

###
GET {{baseUrl}}/tradeLog/myDonations/ing HTTP/1.1
content-type : application/json

<!--  order 안에 campaign에 관련 캠페인 넣어준 구조임
{
  "data": {
    "data": [
      {
        "id": 3,
        "value": 500,
        "transactionId": 123213,
        "createdAt": "2020-05-26T02:08:27.000Z",
        "updatedAt": "2020-05-26T02:08:27.000Z",
        "deletedAt": null,
        "userId": 1,
        "campaignId": 3,
        "campaign": {
          "id": 3,
          "name": "campaign3",
          "title_img": "default.png",
          "dest_money": 100000,
          "current_money": 0,
          "content": "campaign info..............",
          "due_day": "2020-06-20T06:14:26.000Z",
          "owner": "charity1",
          "createdAt": "2020-05-17T11:39:45.000Z",
          "updatedAt": "2020-05-17T11:39:45.000Z",
          "deletedAt": null,
          "userId": 1
        }
      }
    ],
    "msg": "success"
  }
}
-->

///////////////////////////////////////////////////////////////////
// get order detail
///////////////////////////////////////////////////////////////////
###
GET {{baseUrl}}/tradeLog/orderDetail/9 HTTP/1.1
content-type : application/json

//뒤에 orderId

///////////////////////////////////////////////////////////////////
// get orders by campaign id
///////////////////////////////////////////////////////////////////
###
GET {{baseUrl}}/tradeLog/ordersByCampaign/1 HTTP/1.1
content-type : application/json