//@baseUrl = http://ec2-18-191-173-110.us-east-2.compute.amazonaws.com:8080
@baseUrl = http://localhost:8080


///////////////////////////////////////////////////////////////////
// buy point
///////////////////////////////////////////////////////////////////
POST {{baseUrl}}/point/buy HTTP/1.1
content-type : application/json

{
    "value" : 1000
}


///////////////////////////////////////////////////////////////////
// change point
///////////////////////////////////////////////////////////////////
###
POST {{baseUrl}}/point/change HTTP/1.1
content-type : application/json

{
    "value" : 1000
}



