//@baseUrl = http://ec2-18-191-173-110.us-east-2.compute.amazonaws.com:8080
@baseUrl = http://localhost:8080


///////////////////////////////////////////////////////////////////
// buy item 
///////////////////////////////////////////////////////////////////
POST {{baseUrl}}/item/buy HTTP/1.1
content-type : application/json

{
    "itemId" : 1,
    "orderCount" : 3,
    "campaignId" : 1,
    "addr" : "살기좋은 안양시"
}
