name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install node packages
        run: npm install
      - name: Check ESLint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          level: warning
          reporter: github-pr-review
          eslint_flags: '**/*.js'

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install node packages
        run: npm install
      - name: Build project
        run: npm build
